//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by GitVersion.
//
// You can modify this code as we will not overwrite it when re-executing GitVersion
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyFileVersion("0.0.1.0")]
[assembly: AssemblyVersion("0.0.1.0")]
[assembly: AssemblyInformationalVersion("0.0.1-add-gitversion.1+6.Branch.feature-add-gitversion.Sha.bba96bf7f0b6d7aed1966d060789cb2408ca9590")]
